const imagens_2 = [
    { caminho: './../assets/fts-jogos/Astronauta.png', resposta: 'Astronauta' },
    { caminho: './../assets/fts-jogos/Constelacao.png', resposta: 'Constelação' },
    { caminho: './../assets/fts-jogos/Coraçao.png', resposta: 'Coração' },
    { caminho: './../assets/fts-jogos/Foguete.png', resposta: 'Foguete' },
    { caminho: './../assets/fts-jogos/Jupiter.png', resposta: 'Jupiter' },
    { caminho: './../assets/fts-jogos/Meteoro.png', resposta: 'Meteoro' },
    { caminho: './../assets/fts-jogos/Meteoro.png', resposta: 'Meteoro' },
    { caminho: './../assets/fts-jogos/Saturno.png', resposta: 'Saturno' },
    { caminho: './../assets/fts-jogos/Satelite.png', resposta: 'Satelite' },
    { caminho: './../assets/fts-jogos/Telescopio.png', resposta: 'Telescópio' },
    { caminho: './../assets/fts-jogos/BuracoNegro.png', resposta: 'Buraco Negro' },
    { caminho: './../assets/fts-jogos/Explosao.png', resposta: 'Explosao' },
];

const Parrimas2 = [
    {par1: "Casa", par2: "Asa"},
    {par1: "Porta", par2: "Corta"},
    {par1: "Janela", par2: "Vela"},
    {par1: "Quarto", par2: "Sarto"},
    {par1: "Sala", par2: "Mala"},
    {par1: "Cozinha", par2: "Linha"},
    {par1: "Banheiro", par2: "Pioneiro"},
    {par1: "Garagem", par2: "Paisagem"},
    {par1: "Jardim", par2: "Fim"},
    {par1: "Telhado", par2: "Dourado"},
    {par1: "Parede", par2: "Rede"},
    {par1: "Chão", par2: "Pão"},
    {par1: "Teto", par2: "Efeito"},
    {par1: "Escada", par2: "Fada"},
    {par1: "Varanda", par2: "Banda"},
    {par1: "Quintal", par2: "Natal"},
    {par1: "Sótão", par2: "Botão"},
    {par1: "Porão", par2: "Coração"},
    {par1: "Cerca", par2: "Merda"},
    {par1: "Portão", par2: "Camarão"},
    {par1: "Lareira", par2: "Beira"},
    {par1: "Chaminé", par2: "Café"},
    {par1: "Piso", par2: "Aviso"},
    {par1: "Muro", par2: "Futuro"},
    {par1: "Cadeira", par2: "Feira"},
    {par1: "Mesa", par2: "Presa"},
    {par1: "Sofá", par2: "Já"},
    {par1: "Cama", par2: "Drama"},
    {par1: "Armário", par2: "Diário"},
    {par1: "Gaveta", par2: "Caneta"},
    {par1: "Prateleira", par2: "Feira"},
    {par1: "Lâmpada", par2: "Câmpada"},
];

export { imagens_2, Parrimas2 };