const imagens_3 = [
    { caminho: './../assets/fts-jogos/Astronauta.png', resposta: 'Astronauta' },
    { caminho: './../assets/fts-jogos/Constelacao.png', resposta: 'Constelação' },
    { caminho: './../assets/fts-jogos/Estrela.png', resposta: 'Estrela' },
    { caminho: './../assets/fts-jogos/Foguete.png', resposta: 'Foguete' },
    { caminho: './../assets/fts-jogos/Lua.png', resposta: 'Lua' },
    { caminho: './../assets/fts-jogos/Meteoro.png', resposta: 'Meteoro' },
    { caminho: './../assets/fts-jogos/Nuvem.png', resposta: 'Nuvem' },
    { caminho: './../assets/fts-jogos/Planeta.png', resposta: 'Planeta' },
    { caminho: './../assets/fts-jogos/Satelite.png', resposta: 'Satelite' },
    { caminho: './../assets/fts-jogos/Sol.png', resposta: 'Sol' },
    { caminho: './../assets/fts-jogos/Terra.png', resposta: 'Terra' },
    { caminho: './../assets/fts-jogos/Explosao.png', resposta: 'Explosao' },
];

const Parrimas3 = [
    {par1: "Borboleta", par2: "Caneta"},
    {par1: "Elefante", par2: "Gigante"},
    {par1: "Crocodilo", par2: "Pilo"},
    {par1: "Helicóptero", par2: "Espectro"},
    {par1: "Computador", par2: "Amador"},
    {par1: "Enciclopédia", par2: "Média"},
    {par1: "Astronauta", par2: "Flauta"},
    {par1: "Biblioteca", par2: "Estética"},
    {par1: "Microscópio", par2: "Próprio"},
    {par1: "Televisão", par2: "Canção"},
    {par1: "Fotografia", par2: "Geografia"},
    {par1: "Universidade", par2: "Cidade"},
    {par1: "Matemática", par2: "Prática"},
    {par1: "Geometria", par2: "Alegria"},
    {par1: "História", par2: "Vitória"},
    {par1: "Química", par2: "Mímica"},
    {par1: "Física", par2: "Música"},
    {par1: "Biologia", par2: "Tecnologia"},
    {par1: "Astronomia", par2: "Economia"},
    {par1: "Meteorologia", par2: "Filosofia"},
    {par1: "Psicologia", par2: "Sociologia"},
    {par1: "Antropologia", par2: "Ecologia"},
    {par1: "Arqueologia", par2: "Geologia"},
    {par1: "Paleontologia", par2: "Mitologia"},
    {par1: "Zoologia", par2: "Patologia"},
    {par1: "Botânica", par2: "Orgânica"},
    {par1: "Ecossistema", par2: "Sistema"},
    {par1: "Biodiversidade", par2: "Realidade"},
    {par1: "Sustentabilidade", par2: "Responsabilidade"},
    {par1: "Conservação", par2: "Educação"},
    {par1: "Reciclagem", par2: "Mensagem"},
];


export { imagens_3, Parrimas3 };